apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379 # port, target port, node port: https://www.bmc.com/blogs/kubernetes-port-targetport-nodeport/
  selector:
    app: redis
    role: leader
    tier: backend