apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: default # separate database by namespace (like test / prod)
spec:
  type: ExternalName
  externalName: woodstock-stg.cluster-ro-cd7jtnvwy0ja.ap-northeast-1.rds.amazonaws.com
  ports:
    - port: 3306
    
# https://qiita.com/toshihirock/items/7b292218ce82427a40db
# kubectl run testpod --image=centos:6 --restart=Never -i --rm -- dig database.default.svc.cluster.local

# ;; QUESTION SECTION:
# ;database.default.svc.cluster.local. IN	A

# ;; ANSWER SECTION:
# database.default.svc.cluster.local. 5 IN CNAME	woodstock-stg.cluster-ro-cd7jtnvwy0ja.ap-northeast-1.rds.amazonaws.com.
# woodstock-stg.cluster-ro-cd7jtnvwy0ja.ap-northeast-1.rds.amazonaws.com.	5 IN CNAME woodstock-stg-instance-0.cd7jtnvwy0ja.ap-northeast-1.rds.amazonaws.com.
# woodstock-stg-instance-0.cd7jtnvwy0ja.ap-northeast-1.rds.amazonaws.com.	5 IN A 172.21.106.162
