---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongodb-init
  namespace: default
data:
  init.sh: |
    #!/bin/bash
    # Need to wait for the readiness health check to pass so that the mongodb names resolve. This is kind of wonky.
    until ping -c 1 ${HOSTNAME}.mongodb; do
    echo "waiting for DNS (${HOSTNAME}.mongodb)..."
    sleep 2
    done
    until /usr/bin/mongodb --eval 'printjson(db.serverStatus())'; do
    echo "connecting to local mongodb..."
    sleep 2
    done
    echo "connected to local."
    HOST=mongodb-0.mongodb:27017
    until /usr/bin/mongodb --host=${HOST} --eval 'printjson(db.serverStatus())'; do
    echo "connecting to remote mongodb..."
    sleep 2
    done
    echo "connected to remote."
    if [[ "${HOSTNAME}" != 'mongodb-0' ]]; then
    until /usr/bin/mongodb --host=${HOST} --eval="printjson(rs.status())" \
    | grep -v "no replset config has been received"; do
    echo "waiting for replication set initialization"
    sleep 2
    done
    echo "adding self to mongodb-0"
    /usr/bin/mongodb --host=${HOST} \
    --eval="printjson(rs.add('${HOSTNAME}.mongodb'))"
    fi
    if [[ "${HOSTNAME}" == 'mongodb-0' ]]; then
    echo "initializing replica set"
    /usr/bin/mongodb --eval="printjson(rs.initiate(\
    {'_id': 'rs0', 'members': [{'_id': 0, \
    'host': 'mongodb-0.mongodb:27017'}]}))"
    fi
    echo "initialized"