apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
  - name: kuard-tls
    image: gcr.io/kuar-demo/kuard-amd64:blue
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  8443
      name:  https
      protocol: TCP
    volumeMounts:
    - name: tls-certs
      mountPath: "/tls"
      readOnly: true
  imagePullSecrets:
  - name: my-image-pull-secret # kubectl create secret docker-registry my-image-pull-secret --docker-username=<username> --docker-password=<password> --docker-email=<email-address>
  volumes:
  - name: tls-certs
    secret:
      secretName: kuard-tls